### ISSUE TITLE
throws ERR_INVALID_PROTOCOL

### ISSUE THREAD

**Issue by zhenchaoli** [pashasadri/progvis-node#1]
test program:
```
const ProgVis = require('progvis');
const pv = new ProgVis("wa-ideas", 3);

pv.step();
pv.log('response generated');
pv.step();
pv.log('message constructed');
pv.step();
pv.log('message sent');

pv.done();
```

running it throws:
```
 PV_TOKEN=394b0efc115e93dfa4df51ca519b6758 node test.js
_http_client.js:155
    throw new ERR_INVALID_PROTOCOL(protocol, expectedProtocol);
    ^

TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:155:11)
    at Object.request (http.js:50:10)
    at Gzip.cb (/Users/zhenchaoli/workspace/wa-ideas/node_modules/progvis/dist/progvis.js:339:24)
    at Gzip.zlibBufferOnEnd (zlib.js:151:10)
    at Gzip.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_INVALID_PROTOCOL'
}
```

I believe https://github.com/pashasadri/progvis-node/blob/91d8c8127b59c918c4d3abc13d162af39c7aff0c/src/progvis.js#L250

should be comparing against 'https:'
missing a colon

**Comment by pashasadri** [comment]
Thanks for catching that! I just pushed a fix.
